# Cloudflare Pages configuration
name = "chatbot-widget-platform"
compatibility_date = "2023-12-01"

# Build configuration
[build]
command = "pnpm run build"
output_dir = "dist"

# Functions configuration
[functions]
directory = "functions"

# Environment variables (these will be set in the Cloudflare dashboard)
# [vars]
# SUPABASE_URL = ""
# SUPABASE_SERVICE_KEY = ""
# SUPABASE_ANON_KEY = ""
# N8N_BASE_URL = ""
# DEMO_WIDGET_EXPIRY_HOURS = "48" 